export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const DIALOG_LOADING = "DIALOG_LOADING";
export const DIALOG_LOAD_SUCCESS = "DIALOG_LOAD_SUCCESS";
export const DIALOG_LOAD_ERROR = "DIALOG_LOAD_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_ME_LOADING = "GET_ME_LOADING";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const GET_ME_ERROR = "GET_ME_ERROR";

export const MESSAGES_LOADING = "MESSAGES_LOADING";
export const MESSAGES_SUCCESS = "MESSAGES_SUCCESS";
export const MESSAGES_ERROR = "MESSAGES_ERROR";

export const LIST_USERS_LOADING = "LIST_USERS_LOADING";
export const LIST_USERS_SUCCESS = "LIST_USERS_SUCCESS";
export const LIST_USERS_ERROR = "LIST_USERS_ERROR";

export const CREATE_DIALOGS_LOADING = "CREATE_DIALOGS_LOADING";
export const CREATE_DIALOGS_SUCCESS = "CREATE_DIALOGS_SUCCESS";
export const CREATE_DIALOGS_ERROR = "CREATE_DIALOGS_ERROR";
export const FORGOT_PASSWORD_LOADING = "FORGOT_PASSWORD_LOADING";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";

export const SET_PASSWORD_LOADING = "SET_PASSWORD_LOADING";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_ERROR = "SET_PASSWORD_ERROR";

export const UPLOAD_AVATAR_LOADING = "UPLOAD_AVATAR_LOADING";
export const UPLOAD_AVATAR_SUCCESS = "UPLOAD_AVATAR_SUCCESS";
export const UPLOAD_AVATAR_ERROR = "UPLOAD_AVATAR_ERROR";

export const UPLOAD_USERNAME_LOADING = "UPLOAD_USERNAME_LOADING";
export const UPLOAD_USERNAME_SUCCESS = "UPLOAD_USERNAME_SUCCESS";
export const UPLOAD_USERNAME_ERROR = "UPLOAD_USERNAME_ERROR";

export const UPLOAD_PASSWORD_LOADING = "UPLOAD_PASSWORD_LOADING";
export const UPLOAD_PASSWORD_SUCCESS = "UPLOAD_PASSWORD_SUCCESS";
export const UPLOAD_PASSWORD_ERROR = "UPLOAD_PASSWORD_ERROR";

export const DELETE_ACCOUNT_LOADING = "DELETE_ACCOUNT_LOADING";
export const DELETE_ACCOUNT_SUCCESS = "DELETE_ACCOUNT_SUCCESS";
export const DELETE_ACCOUNT_ERROR = "DELETE_ACCOUNT_ERROR";
