export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const DIALOG_LOADING = "DIALOG_LOADING";
export const DIALOG_LOAD_SUCCESS = "DIALOG_LOAD_SUCCESS";
export const DIALOG_LOAD_ERROR = "DIALOG_LOAD_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const GET_ME_LOADING = "GET_ME_LOADING";
export const GET_ME_SUCCESS = "GET_ME_SUCCESS";
export const GET_ME_ERROR = "GET_ME_ERROR";
